### ISSUE TITLE
Error after upgrade to TYPO3 10

### ISSUE THREAD

**Issue by Hogego** [oliverklee/ext-seminars#1220]
Hi Oliver,

could you help me with this?

After upgrading to TYPO3 10.4.21 (from 9.x) I get this mistake after trying to edit an content element (in the BE) of type plugin > seminar

Oops, an error occurred!
TCA internal_type of field "templateFile" in table tt_content must be set to "db" or "folder“.

Thanks a lot!

Ralph

**Comment by oliverklee** [comment]
Hi @Hogego, thanks for the bug report!

Do you get this error when opening an existing content element or when trying to save it?

And could you please check whether clearing all caches helps in any way? Thanks!

**Comment by Hogego** [comment]
Hi Oliver

I’ve cleared all caches
same mistake when opening

**Comment by oliverklee** [comment]
I have just released version 4.1.1 with the fix.

**Comment by Hogego** [comment]
Hi Olver

great, this works!

Another question: I don’t get sr_feuser_register working without the need to set a password.

I just want to use the extension for to register to a seminar and no password ist necessary for this.

I’ve tried 	plugin.tx_srfeuserregister_pi1.generatePassword = 8
but still get the passwort required reply

can you help e with this?

thanks a lot!

**Comment by oliverklee** [comment]
@Hogego That's exactly what I wrote my onetimeaccount extension for: https://extensions.typo3.org/extension/onetimeaccount

**Comment by Hogego** [comment]
yes, but I need it for TYPO 10.x :-(

**Comment by oliverklee** [comment]
@Hogego I'm going to build a 10-compatible onetimeaccount version in the next weeks: https://github.com/oliverklee/ext-seminars/wiki/Project-planning:-10LTS-compatibility#13-rewrite-onetimeaccount-with-extbasefluid-for-typo3-v9-and-v10

**Comment by Hogego** [comment]
Great, thank you!!

**Comment by Hogego** [comment]
Hi Oliver,

sorry, me again

new error after klicking on detail-view in list mode :


Oops, an error occurred!
Too few arguments to function TYPO3Fluid\Fluid\Core\Rendering\RenderingContext::__construct(), 0 passed in /usr/www/users/bfgoea/t3_sites/bfgoe21_10/typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php on line 3313 and exactly 1 expected

/typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php on line 3313 and exactly 1 expected

**Comment by oliverklee** [comment]
@Hogego Could you please create a new ticket for this (so we follow the "one issue per ticket" rule)? Thanks!

And for discussions that are not bug reports of feature requests, I'd like to recommend the discussions feature of GitHub over here: https://github.com/oliverklee/ext-seminars/discussions
